### ISSUE TITLE
Sunday WPI testing

### ISSUE THREAD

**Issue by amorygalili** [frc2423/2023#39]
Things to test on Sunday:
- AprilTags and auto aligning with then (for scoring and picking up game pieces at the human player station)
- Auto modes
- Setpoints for scoring and getting game pieces at human player station

PhotonVision dashboard URL hosted on robot: http://10.24.23.11:5800/
Maybe add vision measurements at a slower rate? https://docs.wpilib.org/en/stable/docs/software/convenience-features/scheduling-functions.html

**Comment by awordforthat** [comment]
EC notes:
- Setpoints probably just need to be tuned - no new code
- Test existing auto modes and tune. If there is downtime, we can add new ones.
- April tag state - test as able.
